// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3fDYP_rqEd00w2g5KYFi2PvqKlu_C7i8',
    appId: '1:565962941142:android:1f17c41c331d4464cf9f77',
    messagingSenderId: '565962941142',
    projectId: 'sri-kot',
    storageBucket: 'sri-kot.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_nyloj_eR2-S4lpwmbbqbG1RCIrTA5DU',
    appId: '1:565962941142:ios:e25d1bf2792fdfb9cf9f77',
    messagingSenderId: '565962941142',
    projectId: 'sri-kot',
    storageBucket: 'sri-kot.appspot.com',
    androidClientId: '565962941142-2e8a60qj2ram8kq7gtlaed34n1iaiev8.apps.googleusercontent.com',
    iosClientId: '565962941142-f0p2sldc374ujvr5g9vrdjj3bunbi495.apps.googleusercontent.com',
    iosBundleId: 'com.srisoftwarez.sriKot',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGcLGZZapYB92-9t_0OM8sPdM9cXzdxC4',
    appId: '1:565962941142:web:4c6ded4efbbdcf39cf9f77',
    messagingSenderId: '565962941142',
    projectId: 'sri-kot',
    authDomain: 'sri-kot.firebaseapp.com',
    storageBucket: 'sri-kot.appspot.com',
    measurementId: 'G-72Q28QXLJB',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_nyloj_eR2-S4lpwmbbqbG1RCIrTA5DU',
    appId: '1:565962941142:ios:e25d1bf2792fdfb9cf9f77',
    messagingSenderId: '565962941142',
    projectId: 'sri-kot',
    storageBucket: 'sri-kot.appspot.com',
    androidClientId: '565962941142-2e8a60qj2ram8kq7gtlaed34n1iaiev8.apps.googleusercontent.com',
    iosClientId: '565962941142-f0p2sldc374ujvr5g9vrdjj3bunbi495.apps.googleusercontent.com',
    iosBundleId: 'com.srisoftwarez.sriKot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGcLGZZapYB92-9t_0OM8sPdM9cXzdxC4',
    appId: '1:565962941142:web:9f741eb253a9028ecf9f77',
    messagingSenderId: '565962941142',
    projectId: 'sri-kot',
    authDomain: 'sri-kot.firebaseapp.com',
    storageBucket: 'sri-kot.appspot.com',
    measurementId: 'G-ZSNZPS0SCS',
  );

}